name: TwoWayPartition
on: [push]
jobs:
  TwoWayPartition:
    name: TwoWayPartition
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: TwoWayPartition
        run: python NumPart.py

      - name: Copy output files to artifact directory
          run: mkdir artifacts
            do
            echo "  Copying OutputFile.txt"
            cp OutputFile.txt artifacts/
            done

      - name: Upload output files to GitHub so they can be reviewed
        uses: actions/upload-artifact@v1
        with:
          name: project_output
          path: artifacts/
